import type { HiringActivityKind } from "@/generated/prisma";

export const HIRING_ACTIVITY_KIND_LABEL: Record<HiringActivityKind, string> = {
  CANDIDATE_CREATED: "Profile created",
  CANDIDATE_DUPLICATE_INTAKE: "Repeat intake (same email)",
  CANDIDATE_UPDATED: "Profile updated",
  APPLICATION_CREATED: "Attached to opening",
  APPLICATION_STAGE_CHANGED: "Pipeline stage updated",
  APPLICATION_NOTES_UPDATED: "Application notes updated",
  APPLICATION_ATTACHMENT_ADDED: "Attachment added",
  APPLICATION_ATTACHMENT_REMOVED: "Attachment removed",
  APPLICATION_DELETED: "Application deleted",
  BULK_APPLICATIONS_DELETED: "Applications bulk-deleted",
  APPLICATION_REVIEW_ADDED: "Feedback added",
  APPLICATION_REVIEW_UPDATED: "Feedback updated",
  APPLICATION_REVIEW_DELETED: "Feedback deleted",
  JOB_CREATED: "Job posting created",
  JOB_UPDATED: "Job posting updated",
  JOB_CLOSED: "Job posting closed",
  JOB_ARCHIVED: "Job removed from listings",
  JOB_RESTORED: "Job restored to listings",
  PIPELINE_STAGE_CREATED: "Pipeline stage added",
  PIPELINE_STAGE_UPDATED: "Pipeline stage updated",
  PIPELINE_STAGE_DELETED: "Pipeline stage removed",
  HIRING_TEMPLATE_CREATED: "Template created",
  HIRING_TEMPLATE_UPDATED: "Template updated",
  HIRING_TEMPLATE_DELETED: "Template deleted",
  APPLICATION_EMAIL_SENT: "Email sent to candidate",
  APPLICATION_INTERVIEW_SCHEDULED: "Interview scheduled",
  REQUISITION_APPROVED: "Requisition approved",
  REQUISITION_REJECTED: "Requisition declined",
};

/** Kinds shown in the activity history filter (stable display order). */
export const HIRING_ACTIVITY_KIND_FILTER_ORDER: HiringActivityKind[] = [
  "APPLICATION_STAGE_CHANGED",
  "APPLICATION_CREATED",
  "APPLICATION_NOTES_UPDATED",
  "APPLICATION_ATTACHMENT_ADDED",
  "APPLICATION_ATTACHMENT_REMOVED",
  "APPLICATION_REVIEW_ADDED",
  "APPLICATION_REVIEW_UPDATED",
  "APPLICATION_REVIEW_DELETED",
  "APPLICATION_EMAIL_SENT",
  "APPLICATION_INTERVIEW_SCHEDULED",
  "APPLICATION_DELETED",
  "BULK_APPLICATIONS_DELETED",
  "CANDIDATE_CREATED",
  "CANDIDATE_UPDATED",
  "CANDIDATE_DUPLICATE_INTAKE",
  "JOB_CREATED",
  "JOB_UPDATED",
  "JOB_CLOSED",
  "JOB_ARCHIVED",
  "JOB_RESTORED",
  "REQUISITION_APPROVED",
  "REQUISITION_REJECTED",
  "PIPELINE_STAGE_CREATED",
  "PIPELINE_STAGE_UPDATED",
  "PIPELINE_STAGE_DELETED",
  "HIRING_TEMPLATE_CREATED",
  "HIRING_TEMPLATE_UPDATED",
  "HIRING_TEMPLATE_DELETED",
];
