-- AlterEnum
ALTER TYPE "HiringActivityKind" ADD VALUE 'APPLICATION_NOTES_UPDATED';
ALTER TYPE "HiringActivityKind" ADD VALUE 'APPLICATION_ATTACHMENT_ADDED';
ALTER TYPE "HiringActivityKind" ADD VALUE 'APPLICATION_ATTACHMENT_REMOVED';
ALTER TYPE "HiringActivityKind" ADD VALUE 'APPLICATION_DELETED';
ALTER TYPE "HiringActivityKind" ADD VALUE 'BULK_APPLICATIONS_DELETED';
ALTER TYPE "HiringActivityKind" ADD VALUE 'APPLICATION_REVIEW_ADDED';
ALTER TYPE "HiringActivityKind" ADD VALUE 'JOB_CREATED';
ALTER TYPE "HiringActivityKind" ADD VALUE 'JOB_UPDATED';
ALTER TYPE "HiringActivityKind" ADD VALUE 'JOB_CLOSED';
ALTER TYPE "HiringActivityKind" ADD VALUE 'JOB_ARCHIVED';
ALTER TYPE "HiringActivityKind" ADD VALUE 'JOB_RESTORED';
ALTER TYPE "HiringActivityKind" ADD VALUE 'PIPELINE_STAGE_CREATED';
ALTER TYPE "HiringActivityKind" ADD VALUE 'PIPELINE_STAGE_UPDATED';
ALTER TYPE "HiringActivityKind" ADD VALUE 'PIPELINE_STAGE_DELETED';
ALTER TYPE "HiringActivityKind" ADD VALUE 'HIRING_TEMPLATE_CREATED';
ALTER TYPE "HiringActivityKind" ADD VALUE 'HIRING_TEMPLATE_UPDATED';
ALTER TYPE "HiringActivityKind" ADD VALUE 'HIRING_TEMPLATE_DELETED';
ALTER TYPE "HiringActivityKind" ADD VALUE 'REQUISITION_APPROVED';
ALTER TYPE "HiringActivityKind" ADD VALUE 'REQUISITION_REJECTED';

-- CreateIndex
CREATE INDEX "HiringActivity_createdAt_idx" ON "HiringActivity"("createdAt");
